ruby_version: 3.1
fix: true
parallel: true

# Ignore existing codebase issues to maintain compatibility
ignore:
  - "lib/llm_team/agents/auxiliary/research_agent/symbolic_math_agent.rb"
  - "lib/llm_team/core/conversation.rb"
  - "lib/llm_team/output.rb"
